language: ruby
rvm:
  - jruby-19mode
  - jruby-head
  - ruby-head
  - rbx
  - 2.2.6
  - 2.3.3
  - 2.4.0
  
install: 
  - gem install minitest
  - gem install rack-test
  - gem install test-unit
  - gem install sinatra
  - gem install rake
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
- rvm: rbx
