language: ruby
rvm:
  - 2.1.10
  - 1.9.3
  - 2.2.6
  - 2.3.3
  - 2.4.0
  
install: 
  - gem install minitest
  - gem install rack-test
  - gem install test-unit
  - gem install sinatra
  - gem install rake
